DZ_F11820_1
yuliyazhukova/itstep pull request #1
Opened 2021-03-16 18:22 UTC by yuliyazhukova

Я даже не знаю правильно ли вообще всё это сделано)))

2021-03-17 08:27 UTC, itstep-mog requested changes

2021-03-17 08:27 UTC, itstep-mog commented on CV.md
> +```
Для блока кода лучше указывать тип языка программирования    ```javascript

2021-03-17 08:27 UTC, itstep-mog commented on CV.md
> +```
Для блока кода лучше указывать тип языка программирования    ```Python

2021-03-17 08:27 UTC, itstep-mog commented on CV.md
> +|||
Это специально реализованный отступ?

2021-03-17 08:35 UTC, yuliyazhukova commented on CV.md
> +|||
Да, я его специально делала

2021-03-18 14:37 UTC, itstep-mog approved these changes

2021-03-18 14:37 UTC, merged